### ISSUE TITLE
Queue logic added in previous PR appears to have gotten lost

### ISSUE THREAD

**Issue by ITJamie** [bitnami/bitnami-docker-airflow-worker#13]
**Description**

Queue logic added to run.sh [here](https://github.com/bitnami/bitnami-docker-airflow-worker/pull/2/files#) appears to have been lost at some point. I've grepped the entire repo and the "AIRFLOW_QUEUE" env variable is no longer referenced anywhere other than the readme.

**Steps to reproduce the issue:**

1. add env var AIRFLOW_QUEUE to a worker. This should limit jobs on this worker to just that queue
2. run any job in airflow that assigns work to the default_queue
3. tasks end up running on the worker setup in step 1 even though it should not have

**Describe the results you received:**

Tasks running against the worker that shoudnt be. 

**Describe the results you expected:**

Tasks that are queued for that worker queue are not being picked up

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:54:27 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:33 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 4
  Running: 4
  Paused: 0
  Stopped: 0
 Images: 10
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.8.0-1039-azure
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 3.791GiB
 Name: airflow
 ID: I37J:KB2J:ETIR:KZ7C:GCKS:MIUB:QGPH:R6KQ:QPIL:MULN:BTHI:VMVN
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

ubuntu vms. using docker-compose and haproxy as a frontend / loadbalancer

**Comment by rafariossaa** [comment]
Hi, 
  Thanks for spotting this. It seems that this was accidentally removed when it was migrated to bash. 
  I am adding this again.

**Comment by ITJamie** [comment]
Do you expect this to be fixed this week?

**Comment by rafariossaa** [comment]
Hi,
  It just has been released in 2.1.2-debian-10-r36.
  Could you take a look if now it works for you ?

**Comment by ITJamie** [comment]
I found that if i give it a list of queues. eg default,foo,bar the first item is ignored... im assuming this is some airflow bug.
This has meant that i am able to get the worker to process tasks

The issue with the worker crashing if i dont give it a queuename will probably need to be sorted though

**Comment by FraPazGal** [comment]
Hello @ITJamie,

Thanks for reporting the issue running the container after adding again queue support. We [modified](https://github.com/bitnami/bitnami-docker-airflow-worker/commit/ed26dd869d90bfe1c853cbcd77ea5fc0096c0e9d) the `celery worker` command and it should now be working properly. Could you check on your side it now works as expected?

**Comment by ITJamie** [comment]
Ill confirm later this evening

**Comment by alemorcuq** [comment]
I have merged #15. Changes should be present in tags `2.1.3-debian-10-r14` and `1.10.15-debian-10-r155`. Can you check them?

**Comment by ITJamie** [comment]
I can confirm it's working as expected now on latest 2.1.3 images. Queues work as expected (it still skips the first one in the list... but thats an airflow bug, i just duplicate the list) when supplied. when the var is not set it defaults to the normal queue. Happy to consider this closed!

Sorry about the delay in getting back but i was fighting a separate issue with the workers and have opened a PR ( https://github.com/bitnami/bitnami-docker-airflow/pull/101 )

**Comment by rafariossaa** [comment]
Hi,
  Thanks for coming back and sharing.
  In that case I am closing this issue.
